spring.application.name=Abarrotes

# El puerto
server.port=8085

# Base de datos H2 PERSISTENTE EN DISCO (Crea una carpeta 'data' al lado del .jar)
spring.datasource.url=jdbc:h2:file:./data/tiendadb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Que Spring cree las tablas autom\u00e1ticamente si no existen o las actualice
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Consola web
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# EL ESCUDO ANTI-ERROR 400: Forzar codificaci\u00f3n UTF-8 en todas las peticiones
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.tomcat.uri-encoding=UTF-8