spring.application.name=Abarrotes

# El puerto
server.port=8085

# Base de datos en memoria (CON EL SEGURO ANTI-BORRADO)
spring.datasource.url=jdbc:h2:mem:tiendadb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Que Spring cree las tablas autom\u00e1ticamente si no existen
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Consola web
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console